openapi: 3.1.0

info:
  title: PyJobs API
  description: API for listing and applying for Python jobs
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: local development server
  - url: https://pyjobs.works
    description: production server

paths:
  /applications:
    get:
      summary:
      operationId:
      responses:
        200:
          description:
          content:
            application/json:
              schema:
    post:
      summary:
      operationId:
      requestBody:
        required: true
        content:
          application/json:
            schema:
      responses:
        201:
          description:
          content:
            application/json:
              schema:
  /applications/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
    get:
      summary:
      operationId:
      responses:
        200:
          description:
          content:
            application/json:
              schema:
        404:
    put:
      summary:
      operationId:
      requestBody:
        required: true
        content:
          application/json:
            schema:
      responses:
        200:
          description:
          content:
            application/json:
              schema:
        404:
    delete:
      summary:
      operationId:
      responses:
        200:
        404:
  /applications/{id}/cancel:
    parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
    post:
      summary:
      operationId:
      requestBody:
        required: true
        content:
          application/json:
            schema:
      responses:
        201:
          description:
          content:
            application/json:
              schema:
        404:

components:
  schemas:
    Application: